# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animate_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61nimate_service.proto\x12\x0e\x61nimateservice\"#\n\x0e\x41nimateRequest\x12\x11\n\timage_url\x18\x01 \x01(\t\"\'\n\x0f\x41nimateResponse\x12\x14\n\x0cmaterial_url\x18\x01 \x01(\t2a\n\x0e\x41nimateService\x12O\n\x0cProcessImage\x12\x1e.animateservice.AnimateRequest\x1a\x1f.animateservice.AnimateResponseB\x12Z\x10./animateserviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'animate_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020./animateservice'
  _globals['_ANIMATEREQUEST']._serialized_start=41
  _globals['_ANIMATEREQUEST']._serialized_end=76
  _globals['_ANIMATERESPONSE']._serialized_start=78
  _globals['_ANIMATERESPONSE']._serialized_end=117
  _globals['_ANIMATESERVICE']._serialized_start=119
  _globals['_ANIMATESERVICE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
